# Generated by Django 5.0.1 on 2024-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id',
            new_name='company_id',
        ),
    ]
